version: "3"
services:

  db:
    build: ./db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: statfive
      MYSQL_DATABASE: statfive
      MYSQL_USER: statfive
      MYSQL_PASSWORD: statfive

  app:
    build: ./
    links:
      - db
    ports:
      - "5001:5000"
      - "9000:9000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: statfive
      MYSQL_USER: statfive
      MYSQL_PASSWORD: statfive
      MYSQL_HOST: db
      PROD: docker